service: build-resources

custom:
  environment: ${opt:environment, 'dev'}
provider:
  name: aws
  runtime: nodejs12.x

functions:
  build:
    handler: handler.build
    environment:
      BUCKET_NAME: 'api-gateway-lopes'
  deployment:
    handler: handler.deployment
    environment:
      stage: ${self:custom.environment}
      apiName: ${env:API_NAME}
      restApiId:
        Fn::ImportValue: ${env:API_NAME}-RestApiId
  basemapping:
    handler: handler.basemapping
    environment:
      stage: ${self:custom.environment}
      apiName: ${env:API_NAME}
      restApiId: 
        Fn::ImportValue: ${env:API_NAME}-RestApiId
  usageplan:
    handler: handler.updateUsagePlanByStage
    environment:
      stage: ${self:custom.environment}
      apiName: ${env:API_NAME}
      restApiId: 
        Fn::ImportValue: ${env:API_NAME}-RestApiId
  usageplanbymethod:
    handler: handler.updateUsagePlanByStageAndMethod
    environment:
      stage: ${self:custom.environment}
      apiName: ${env:API_NAME}
      restApiId: 
        Fn::ImportValue: ${env:API_NAME}-RestApiId
  updatestage:
    handler: handler.updateStage
    environment:
      stage: ${self:custom.environment}
      apiName: ${env:API_NAME}
      restApiId: 
        Fn::ImportValue: ${env:API_NAME}-RestApiId

plugins:
  - serverless-plugin-scripts
  - serverless-plugin-typescript
