service: build-resources

provider:
  name: aws
  runtime: nodejs12.x

functions:
  build:
    handler: handler.build
  cloudFormation:
    handler: handler.cloudFormation
  deployment:
    handler: handler.deployment
    environment:
      stage: ${opt:environment}
      restApiId: 
        Fn::ImportValue: ${env:API_NAME}-RestApiId
  basemapping:
    handler: handler.basemapping
    environment:
      stage: ${opt:environment}
      restApiId: 
        Fn::ImportValue: ${env:API_NAME}-RestApiId

plugins:
  - serverless-plugin-scripts
  - serverless-plugin-typescript
