service: base-mapping-api-gw
custom:
  stages:
    - dev
    - qa
    - stg
    - prd
  stage: ${opt:stage, self:provider.stage}
  file: file(./config/${self:custom.stage}.config.yml)
provider:
  name: aws
  stage: dev
resources:
  Resources: 
    ApiGatewayBaseMapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties: 
        BasePath: ${env:API_CONTEXT}
        DomainName: ${${self:custom.file}:domainName}
        RestApiId: 
            Fn::ImportValue: ${env:API_NAME}-RestApiId
        Stage: '${self:custom.stage}'
plugins:
  - serverless-stage-manager